# Generated by Django 4.1.4 on 2022-12-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("testing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="categorytest",
            name="poster",
            field=models.ImageField(null=True, upload_to="uploads/"),
        ),
    ]
